services:
  - type: web
    name: my-calculator
    runtime: node
    region: ohio
    plan: free
    buildCommand: |
      chmod +x amplify-build.sh
      ./amplify-build.sh
    startCommand: cd build/server && NODE_ENV=production PORT=5002 USE_PROXY=false npm run deploy
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5002
      - key: API_URL
        value: https://calcobee.com
      - key: CORS_ORIGIN
        value: https://calcobee.com,https://www.calcobee.com
      - key: USE_PROXY
        value: false
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
    routes:
      - type: rewrite
        source: /api/*
        destination: /api/$1
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true
